global:
  ## A more powerful alternative to Helm's limited YAML anchors. Avoids duplicating configuration across multiple apps.
  #
  # Configuration blocks are declared here under global._includes and can be referenced anywhere in values files.
  # Example of referencing a block:
  # -----------------------------------------------------------------------------------------------
  # .helm/values.yaml:
  # -----------------------------------------------------------------------------------------------
  # apps-cronjobs:
  #   cronjob-1:
  #     _include: ["apps-cronjobs-defaultCronJob"]
  #     backoffLimit: 1
  # -----------------------------------------------------------------------------------------------
  #
  # In the example above, the include block expands at apps-cronjobs.cronjob-1 level; then backoffLimit: 1 is merged on top, overriding the value from the block.
  #
  _includes:
    # _include_from_file merges YAML from the specified file; works anywhere in values.yaml
    _include_from_file: helm-apps-defaults.yaml



