name: Release Charts

on:
  push:
    branches:
    - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Set lib version
      run: |
        LIB_VERSION=$(sed -n '/version/{s/version: //;p;}' charts/helm-apps/Chart.yaml)
        sed -i 's/_FLANT_APPS_LIBRARY_VERSION_/'${LIB_VERSION}'/' charts/helm-apps/templates/_apps-version.tpl

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Install Dyff
      run: |
        sudo snap install dyff

    - name: Helm dependency update
      run: |
        cd tests && helm dependency update .helm

    - name: Render
      run: |
        set -e
        cd tests && helm template tests .helm --namespace test-prod --set "global._includes.apps-defaults.enabled=true" --set "global.env=prod"

    - name: Test render
      run: |
        set -e
        cd tests && helm template tests .helm --namespace test-prod --set "global._includes.apps-defaults.enabled=true" --set "global.env=prod" > test_render_check.yaml
        dyff between test_render.yaml test_render_check.yaml

    - name: Run chart-releaser
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: helm/chart-releaser-action@v1.7.0
      with:
        charts_dir: charts
        config: cr.yaml
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
